words:
  - bezier
  - canvaskit
  - chartext
  - embind
  - mantine
  - preinstall
  - quantiles
  - roboto
  - skia
  - syncpack
  - threaddot
  - tinycolor
  - treeshake
  - tsbuildinfo
  - vite
  - webgpu
