name: Check linting

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  pnpm-install:
    uses: ./.github/workflows/pnpm-install.yml
  lint:
    needs: pnpm-install
    runs-on: ubuntu-latest
    steps:
      - name: Check linting
        run: pnpm lint:check
