name: Deploy pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  pnpm-install:
    uses: ./.github/workflows/pnpm-install.yml
  build:
    needs: pnpm-install
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: pnpm examples:chart build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './examples/chart/dist'
  deploy:
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy pages
        id: deployment
        uses: actions/deploy-pages@v2
